imp/hw_improv/hw_improv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]


# from django.conf import settings
# from django.conf.urls.static import static

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

imp/hw_improv/quotes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name = 'root'),
    path('<int:page>', views.main, name = 'root_paginate'),


    path("add_author/", views.add_author, name="add_author"),
    path("add_quote/", views.add_quote, name="add_quote"),
    path('quotes/', login_required(views.main), name='quotes'),
    path('author/<str:author_id>/', views.about, name='author'),
    path('author/<str:author_id>/', views.author_detail, name='author_detail'),

]

imp/hw_improv/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

from django.urls import path
from . import views

from .forms import LoginForm


app_name = "users"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="signup"),


    path("login/", LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                     authentication_form=LoginForm), name="login"),

    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
]

imp/hw_improv/quotes/models.py
from django.db import models
from django.contrib.auth.models import User



class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.fullname

class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    def __str__(self):
        return self.name

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

imp/hw_improv/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateInput, DateField
from .models import Tag, Author, Quote



class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']



class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    born_date = DateField(required=False, widget=DateInput())
    born_location = CharField(max_length=50, required=False, widget=TextInput())
    description = CharField(required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'description']
        exclude = ['born_date', 'born_location']




class QuoteForm(ModelForm):
    quote = CharField(min_length=10, max_length=500, required=True, widget=TextInput())
    tags = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    author = CharField(min_length=5, max_length=50, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['tags', 'author'] # які поля моделі слід виключити з форми

imp/hw_improv/quotes/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404

from django.core.paginator import Paginator, EmptyPage

from .forms import AuthorForm, QuoteForm
from django.contrib.auth.decorators import login_required
from .models import Author, Tag
from .models import Quote

from .utils import get_mongodb
from .templatetags.extract import get_author_and_quotes

import logging
logger = logging.getLogger(__name__)


def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user  # Встановлення користувача
            author.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_author.html', {'form': form})
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})


def about(request, author_id):
    author, quotes = get_author_and_quotes(author_id)

    if author is None:
        return render(request, 'quotes/author_not_found.html', {'author_id': author_id})

    context = {
        'author_id': author_id,
        'quotes': quotes,
        'author': author,
    }
    logger.info("Rendering page for author: %s", author['fullname'])
    return render(request, 'quotes/author.html', context)



def author_detail(request, author_id):
    try:
        author = Author.objects.get(pk=author_id)
        quotes = Quote.objects.filter(author=author)
        return render(request, 'quotes/author_detail.html', {'author': author, 'quotes': quotes})
    except Author.DoesNotExist:
        return render(request, 'quotes/author_not_found.html', {'author_id': author_id})


@login_required
def add_quote(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quotes:root')

        else:
            return render(request, 'quotes/add_quote.html', {"tags": tags, 'form': form})

    return render(request, 'quotes/add_quote.html', {"tags": tags, 'form': QuoteForm()})

imp/hw_improv/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-md-8 mt-4">
                        <label>Author name</label>
                        {{ form.fullname }}
                        <span>{{ form.errors.fullname }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-8 mt-4">
                        <label>Descriptions : </label>
                        {{ form.description }}
                        <span>{{ form.errors.description }}</span>
                    </div>
                </div>
                <div class="form-group mt-4 mb-4">
                    <button type="submit" class="btn btn-success">Add</button>
                </div>
                <div class="form-group">
                    <div class="col-md-8 mt-4">
                        <span>{{ form.errors }}</span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

imp/hw_improv/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{%block content%}

<div class="container">
    <div class="row justify-content-center">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-row mb-4">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Quote</label>
                            {{ form.quote }}
                            <span>{{ form.errors.quote }}</span>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Tags</label>
                            {{ form.tags }}
                            <span>{{ form.errors.tags }}</span>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label>Author</label>
                            {{ form.author }}
                            <span>{{ form.errors.author }}</span>
                        </div>
                    </div>
                </div>
                <div class="form-group mt-4 text-end">
                    <button type="submit" class="btn btn-success">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

imp/hw_improv/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}
{% block content %}
    <div class="author-details">
        <h3 class="author-title">{{ author.fullname }}</h3>
        <!-- <p><strong>Description:</strong> {{ author.description }}</p> -->

        <h3>Quotes</h3>
        <!-- {{ quotes|safe }} -->
        
        <!-- Quotes for Author {{ author_id }} -->
        <div>
            
                <p>{{ quotes|escape }}</p>
            
        </div>



        {% for quote in quotes_by_author %}
        <div class="quote">
            <p>{{ quote.quote }}</p>
            <div class="tags">
                Tags: {% for tag in quote.tags.all %}
                    <a class="tag" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

    </div>
{% endblock %}

imp/hw_improv/quotes/templates/quotes/author_not_found.html
{% extends 'quotes/base.html' %}
{% block content %}
    <div class="author-details">
        <h3 class="author-title">Author Not Found</h3>
        <p>No author found with ID: {{ author_id }}</p>
    </div>
{% endblock %}

imp/hw_improv/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}"/>
    <!-- <link rel="stylesheet" href="/static/quotes/style.css"/> -->
    
    <title>Homework10</title>
  </head>

  <body>
    <div class="container">
      <div class="row header-box pt-4">
          <div class="col-md-8">
              <h1>
                  <a href="/" style="text-decoration: none">Quotes to Scrape</a>
              </h1>
          </div>
          <div class="col-md-4">
              <p>
                {% if user.is_authenticated %}
              
                  <!-- <a href="/signup/" class="btn btn-primary"> SignUp </a> -->

                  <a href="{% url 'users:logout' %}" class="btn btn-primary"> LogOut </a>
                  <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author </a>
                  <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote </a>
 

                {% else %}
                  <a href="{% url 'users:signup' %}" class="btn btn-primary"> SignUp </a>
                  <a href="{% url 'users:login' %}" class="btn btn-primary"> Login </a>
                {% endif %}
              
              </p>
          </div>
      </div>
      {% block content %} {% endblock %}

    </div>
    


  </body>
</html>

imp/hw_improv/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
  <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text"> {{quote.quote}} </span>
      <span>
        by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
      </span>
      <div class="tags">
        Tags: {% for tag in quote.tags %}
        <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
        {% endfor %}
      </div>
    </div>
    {% endfor %}

    <h1>All Authors and Quotes</h1>
    <ul>
      {% for author in authors %}
        <li>{{ author.fullname }}</li>
        {% if author.quote_set.all %}
          <ul>
            {% for quote in author.quote_set.all %}
            <li>{{ quote.quote }}</li>
            {% endfor %}
          
          </ul>
        {% endif %}
      {% endfor %}
    </ul>
    

    <nav>
      <ul class="pager">
        <li class="previous">
          <a class="{% if not quotes.has_previous %} disabled {% endif %}" href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
            <span aria-hidden="true">←</span> Previous
          </a>
        </li>

        <li class="next">
          <a class="{% if not quotes.has_next %} disabled {% endif %}" href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
            Next <span aria-hidden="true">→</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>

{% endblock %}